/**
 * Teacher Export Engine for Raja Rocket Flow
 * Generates formatted sequence handouts based on export_research.json
 * Supports: Teacher Cheat Sheet, Student Study Guide, Social Media Pack
 */

// Generate HTML for PDF export
function generateCheatSheetHTML(sequence, branding = {}) {
  const { teacherName = '', studioName = '' } = branding;
  const poses = sequence.poses || [];

  let poseRows = '';
  poses.forEach((pose, i) => {
    if (i % 4 === 0) poseRows += '<tr>';
    poseRows += `
      <td style="padding: 8px; border: 1px solid #e0e0e0; text-align: center; width: 25%;">
        <div style="font-size: 24px; margin-bottom: 4px;">🧘</div>
        <div style="font-weight: 600; font-size: 11px; color: #333;">${pose.english_name}</div>
        <div style="font-size: 9px; color: #999; font-style: italic;">${pose.sanskrit_name || ''}</div>
        <div style="font-size: 9px; color: #FF6B35; margin-top: 2px;">${pose.duration || 5} breaths</div>
      </td>`;
    if (i % 4 === 3 || i === poses.length - 1) poseRows += '</tr>';
  });

  return `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', 'Arial', sans-serif; margin: 20px; color: #333; }
          .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #FF6B35; }
          .header h1 { color: #2C2C2C; font-size: 22px; margin: 0; }
          .header .subtitle { color: #999; font-size: 12px; margin-top: 4px; }
          .header .branding { color: #FF6B35; font-size: 11px; margin-top: 6px; font-weight: 600; }
          table { width: 100%; border-collapse: collapse; }
          td { vertical-align: top; }
          .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #e0e0e0; font-size: 9px; color: #999; text-align: center; }
          .stats { text-align: center; margin: 15px 0; font-size: 11px; color: #666; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${sequence.name || 'Rocket Flow'}</h1>
          <div class="subtitle">Teacher Cheat Sheet · ${poses.length} poses</div>
          ${teacherName ? `<div class="branding">${teacherName}${studioName ? ` · ${studioName}` : ''}</div>` : ''}
        </div>
        <div class="stats">
          Total: ${poses.reduce((s, p) => s + (p.duration || 5), 0)} breaths · 
          ${poses.filter(p => p.target_body_parts?.includes('Full Body')).length > 0 ? 'Full Body' : ''}
        </div>
        <table>${poseRows}</table>
        <div class="footer">
          Generated by Raja Rocket Flow · ${new Date().toLocaleDateString()}
          ${sequence.remixLink ? ` · Remix at ${sequence.remixLink}` : ''}
        </div>
      </body>
    </html>`;
}

function generateStudyGuideHTML(sequence, branding = {}) {
  const { teacherName = '', studioName = '' } = branding;
  const poses = sequence.poses || [];

  let poseDetails = '';
  poses.forEach((pose, i) => {
    poseDetails += `
      <div style="margin-bottom: 12px; padding: 12px; border: 1px solid #e0e0e0; border-radius: 8px; page-break-inside: avoid;">
        <div style="display: flex; align-items: center; margin-bottom: 6px;">
          <span style="background: #FF6B35; color: white; border-radius: 50%; width: 24px; height: 24px; display: inline-flex; align-items: center; justify-content: center; font-size: 11px; font-weight: 700; margin-right: 10px;">${i + 1}</span>
          <div>
            <span style="font-weight: 700; font-size: 14px; color: #2C2C2C;">${pose.english_name}</span>
            <span style="font-size: 11px; color: #999; font-style: italic; margin-left: 6px;">(${pose.sanskrit_name || ''})</span>
          </div>
        </div>
        <div style="margin-left: 34px; font-size: 12px; color: #666;">
          <div><strong>Duration:</strong> ${pose.duration || 5} breaths</div>
          <div><strong>Focus:</strong> ${(pose.target_body_parts || []).join(', ')}</div>
        </div>
      </div>`;
  });

  return `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', 'Arial', sans-serif; margin: 20px; color: #333; }
          .header { text-align: center; margin-bottom: 20px; padding-bottom: 15px; border-bottom: 2px solid #004E89; }
          .header h1 { color: #2C2C2C; font-size: 24px; margin: 0; }
          .header .subtitle { color: #999; font-size: 12px; margin-top: 4px; }
          .header .branding { color: #004E89; font-size: 11px; margin-top: 6px; font-weight: 600; }
          .footer { margin-top: 20px; padding-top: 10px; border-top: 1px solid #e0e0e0; font-size: 9px; color: #999; text-align: center; }
          .overview { margin-bottom: 20px; padding: 15px; background: #f8f8f8; border-radius: 8px; font-size: 12px; }
        </style>
      </head>
      <body>
        <div class="header">
          <h1>${sequence.name || 'Rocket Flow'}</h1>
          <div class="subtitle">Student Study Guide · ${poses.length} poses</div>
          ${teacherName ? `<div class="branding">${teacherName}${studioName ? ` · ${studioName}` : ''}</div>` : ''}
        </div>
        <div class="overview">
          <strong>Sequence Overview:</strong> ${poses.length} poses · Total ${poses.reduce((s, p) => s + (p.duration || 5), 0)} breaths<br>
          <strong>Experience Level:</strong> ${sequence.experienceLevel || 'intermediate'}<br>
          <strong>Rocket Sequence:</strong> ${sequence.rocketSequence ? `Rocket ${sequence.rocketSequence}` : 'Custom'}
        </div>
        ${poseDetails}
        <div class="footer">
          Generated by Raja Rocket Flow · ${new Date().toLocaleDateString()}
          ${sequence.remixLink ? ` · Remix at ${sequence.remixLink}` : ''}
        </div>
      </body>
    </html>`;
}

function generateSocialMediaHTML(sequence, format = 'square') {
  const poses = sequence.poses || [];
  const isSquare = format === 'square';
  const posesPerRow = isSquare ? 3 : 4;

  let poseGrid = '';
  poses.slice(0, 12).forEach((pose, i) => {
    if (i % posesPerRow === 0) poseGrid += '<tr>';
    poseGrid += `
      <td style="padding: 6px; text-align: center; width: ${100/posesPerRow}%;">
        <div style="font-size: 20px;">🧘</div>
        <div style="font-size: 8px; font-weight: 600; color: #333; margin-top: 2px;">${pose.english_name}</div>
      </td>`;
    if (i % posesPerRow === posesPerRow - 1 || i === Math.min(poses.length, 12) - 1) poseGrid += '</tr>';
  });

  return `
    <html>
      <head>
        <style>
          body { font-family: 'Helvetica', 'Arial', sans-serif; margin: 0; padding: 20px; width: ${isSquare ? '800' : '1080'}px; height: ${isSquare ? '800' : '1920'}px; background: linear-gradient(135deg, #FF6B35 0%, #FFB347 100%); color: white; }
          .content { padding: 20px; }
          h1 { font-size: 32px; margin: 0 0 4px 0; text-align: center; }
          .subtitle { text-align: center; font-size: 14px; opacity: 0.9; margin-bottom: 20px; }
          table { width: 100%; border-collapse: collapse; }
          td { background: rgba(255,255,255,0.15); border-radius: 8px; }
          .footer { text-align: center; margin-top: 20px; font-size: 11px; opacity: 0.8; }
        </style>
      </head>
      <body>
        <div class="content">
          <h1>${sequence.name || 'Rocket Flow'}</h1>
          <div class="subtitle">${poses.length} poses · ${sequence.experienceLevel || 'intermediate'}</div>
          <table>${poseGrid}</table>
          <div class="footer">Build yours at Raja Rocket Flow</div>
        </div>
      </body>
    </html>`;
}

/**
 * Generate export HTML based on format type
 */
export function generateExportHTML(sequence, format, branding = {}) {
  switch (format) {
    case 'cheat-sheet':
      return generateCheatSheetHTML(sequence, branding);
    case 'study-guide':
      return generateStudyGuideHTML(sequence, branding);
    case 'social-square':
    case 'social-vertical':
      return generateSocialMediaHTML(sequence, format === 'social-square' ? 'square' : 'vertical');
    default:
      return generateCheatSheetHTML(sequence, branding);
  }
}

/**
 * Get available export formats
 */
export function getExportFormats() {
  return [
    { id: 'cheat-sheet', name: "Teacher's Cheat Sheet", description: 'Visual grid (4 poses/row) for in-studio reference', icon: 'grid' },
    { id: 'study-guide', name: 'Student Study Guide', description: 'Detailed list with alignment cues and breath counts', icon: 'list' },
    { id: 'social-square', name: 'Social Media (Square)', description: '1:1 aspect ratio for Instagram posts', icon: 'square' },
    { id: 'social-vertical', name: 'Social Media (Story)', description: '9:16 aspect ratio for Instagram Stories', icon: 'phone-portrait' },
  ];
}

/**
 * Generate a shareable remix link for embedding in exports
 */
export function generateRemixLink(slug) {
  if (!slug) return null;
  return `https://rajarocket.app/shared/${slug}`;
}
